### ISSUE TITLE
AVIF images lacking file extension in URL are not found

### ISSUE THREAD

**Issue by estubmo** [coollabsio/next-image-transformation#3]
The following image will give an error when passed through the proxy.
https://vcdn.polarismedia.no/77ad7bce-c115-407d-b82d-d42dd0cf3707?fit=crop&w=400&h=200&q=80&tight=false

As such:
https://next-image-transform.fotballfeber.com/image/https://vcdn.polarismedia.no/77ad7bce-c115-407d-b82d-d42dd0cf3707?fit=crop&w=400&h=200&q=80&tight=false
`Source image is unreachable`

Logs:
```
Completed in 63.353636ms /pr:sharp/resize:fill:0:0/q:75/plain/https://vcdn.polarismedia.no/77ad7bce-c115-407d-b82d-d42dd0cf3707@webp  request_id=YX4uHc_LnohczlpnjQnvg method=GET status=404 client_ip=172.23.48.3 error="Can't download source image: Status: 400; {\"code\":400,\"message\":\"Invalid signature\"}"
```

I tried setting the env var `IMGPROXY_ENABLE_AVIF_DETECTION=true` as per the [imgproxy docs](https://docs.imgproxy.net/configuration/options#avifwebp-support-detection), but it does not work.

I believe the issue is in this line: https://github.com/coollabsio/next-image-transformation/blob/main/index.js#L36

When @webp is set in the url env vars such as `IMGPROXY_ENABLE_WEBP_DETECTION` and `IMGPROXY_ENABLE_AVIF_DETECTION` will not work.

**Comment by andrasbacsai** [comment]
It seems that only browsers can access this [image](https://vcdn.polarismedia.no/77ad7bce-c115-407d-b82d-d42dd0cf3707). When I try with curl, I encounter the same error.

What type of CDN are you using to serve that image? Is this your image or just a random one?

**Comment by estubmo** [comment]
It's just a random image, unfortunately, so I don't know which CDN they are using.

**Comment by andrasbacsai** [comment]
I will investigate that exact image.

However, I fixed the avif detection and removed the `webp` forced extension.

**Comment by estubmo** [comment]
Thank you! Good work :)
